export const BANK_IMAGE_DATA: {
  image: string;
  bankFullName: string;
  abbreviation: string;
  issuerCode: string;
  code: string;
}[] = [
  {
    image: 'img_nhnn',
    bankFullName: 'Ngân hàng Nhà nước Việt Nam',
    abbreviation: 'NHNN',
    issuerCode: '',
    code: '01101100',
  },
  {
    image: 'img_vietinbank',
    bankFullName: 'Ngân hàng TMCP Công Thương Việt Nam',
    abbreviation: 'VietinBank',
    issuerCode: '970415',
    code: '01201001',
  },
  {
    image: 'img_bidv',
    bankFullName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    abbreviation: 'BIDV',
    issuerCode: '970418',
    code: '01202001',
  },
  {
    image: 'img_vcb',
    bankFullName: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    abbreviation: 'Vietcombank',
    issuerCode: '970436',
    code: '01203001',
  },
  {
    image: 'img_vba',
    bankFullName: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    abbreviation: 'Agribank',
    issuerCode: '970405',
    code: '01204001',
  },
  {
    image: 'img_vbsp',
    bankFullName: 'Ngân hàng TMCP Chính sách Xã hội',
    abbreviation: 'VBSP',
    issuerCode: '999888',
    code: '01207001',
  },
  {
    image: 'img_vdb',
    bankFullName: 'Ngân hàng TMCP Phát triển Việt Nam',
    abbreviation: 'VDBank',
    issuerCode: '',
    code: '01208001',
  },
  {
    image: 'img_mafc',
    bankFullName: 'Ngân hàng TMCP Hàng Hải Việt Nam',
    abbreviation: 'Maritime Bank',
    issuerCode: '970426',
    code: '01302001',
  },
  {
    image: 'img_scb',
    bankFullName: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    abbreviation: 'Sacombank',
    issuerCode: '970403',
    code: '79303001',
  },
  {
    image: 'img_dab',
    bankFullName: 'Ngân hàng TMCP Đông Á',
    abbreviation: 'DongA Bank',
    issuerCode: '970406',
    code: '79304001',
  },
  {
    image: 'img_eib',
    bankFullName: 'Ngân hàng TMCP Xuất nhập khẩu Việt Nam',
    abbreviation: 'Eximbank',
    issuerCode: '970431',
    code: '79305001',
  },
  {
    image: 'img_namabank',
    bankFullName: 'Ngân hàng TMCP Nam Á',
    abbreviation: 'Nam A Bank',
    issuerCode: '970428',
    code: '01306001',
  },
  {
    image: 'img_acb',
    bankFullName: 'Ngân hàng TMCP Á Châu',
    abbreviation: 'ACB',
    issuerCode: '970416',
    code: '79307001',
  },
  {
    image: 'img_sgb',
    bankFullName: 'Ngân hàng TMCP Sài Gòn Công Thương',
    abbreviation: 'Sai Gon Bank',
    issuerCode: '970400',
    code: '79308001',
  },
  {
    image: 'img_vpb',
    bankFullName: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    abbreviation: 'VPBank',
    issuerCode: '970432',
    code: '01309001',
  },
  {
    image: 'img_tcb',
    bankFullName: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    abbreviation: 'Techcombank',
    issuerCode: '970407',
    code: '01310001',
  },
  {
    image: 'img_mb',
    bankFullName: 'Ngân hàng TMCP Quân Đội',
    abbreviation: 'MBBank',
    issuerCode: '970422',
    code: '01311001',
  },
  {
    image: 'img_nasb',
    bankFullName: 'Ngân hàng TMCP Bắc Á',
    abbreviation: 'Bac A Bank',
    issuerCode: '970409',
    code: '40313001',
  },
  {
    image: 'img_vib',
    bankFullName: 'Ngân hàng TMCP Quốc tế Việt Nam',
    abbreviation: 'VIB',
    issuerCode: '970441',
    code: '79314013',
  },
  {
    image: '',
    bankFullName: 'NH TMCP VUNG TAU',
    abbreviation: 'TMCP VUNG TAU',
    issuerCode: '',
    code: '01315001',
  },
  {
    image: 'img_seab',
    bankFullName: 'Ngân hàng TMCP Đông Nam Á',
    abbreviation: 'SeABank',
    issuerCode: '970440',
    code: '01317001',
  },
  {
    image: 'img_ojb',
    bankFullName: 'Ngân hàng TMCP Đại Dương',
    abbreviation: 'Ocean Bank',
    issuerCode: '970414',
    code: '01319001',
  },
  {
    image: 'img_gpb',
    bankFullName: 'Ngân hàng TMCP Dầu Khí Toàn Cầu',
    abbreviation: 'GPBank',
    issuerCode: '970408',
    code: '01320001',
  },
  {
    image: 'img_hdb',
    bankFullName: 'Ngân hàng TMCP Phát Triển TP HCM',
    abbreviation: 'HDBank',
    issuerCode: '970437',
    code: '79321001',
  },
  {
    image: 'img_abbank',
    bankFullName: 'Ngân hàng TMCP An Bình',
    abbreviation: 'ABBank',
    issuerCode: '970425',
    code: '01323002',
  },
  {
    image: '',
    bankFullName: 'NH TMCP VIET HOA HCM',
    abbreviation: 'VIET HOA',
    issuerCode: '',
    code: '79324001',
  },
  {
    image: 'img_bvb',
    bankFullName: 'Ngân hàng TMCP Bản Việt',
    abbreviation: 'BVBank',
    issuerCode: '970454',
    code: '79327001',
  },
  {
    image: 'img_timo',
    bankFullName: 'BVBank Timo - Ngân hàng số Timo',
    abbreviation: 'BVBank Timo',
    issuerCode: '963388',
    code: '79327001T',
  },
  {
    image: 'img_ocb',
    bankFullName: 'Ngân hàng TMCP Phương Đông',
    abbreviation: 'OCB',
    issuerCode: '970448',
    code: '79333001',
  },
  {
    image: 'img_liobank',
    bankFullName: 'Ngân hàng số Liobank by OCB',
    abbreviation: 'Liobank',
    issuerCode: '963369',
    code: '79333001L',
  },
  {
    image: 'img_scb',
    bankFullName: 'Ngân hàng TMCP Sài Gòn',
    abbreviation: 'SCB',
    issuerCode: '970429',
    code: '79334001',
  },
  {
    image: 'img_cbbank',
    bankFullName: 'Ngân hàng TM TNHH MTV Xây Dựng Việt Nam ',
    abbreviation: 'CBBank',
    issuerCode: '970444',
    code: '80339001',
  },
  {
    image: 'img_pgb',
    bankFullName: 'Ngân hàng TMCP Thịnh vượng và Phát triển',
    abbreviation: 'PG BANK',
    issuerCode: '970430',
    code: '01341001',
  },
  {
    image: 'img_shb',
    bankFullName: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    abbreviation: 'SHB',
    issuerCode: '970443',
    code: '01348002',
  },
  {
    image: 'img_ncb',
    bankFullName: 'Ngân hàng TMCP Quốc Dân',
    abbreviation: 'NCB',
    issuerCode: '970419',
    code: '01352002',
  },
  {
    image: 'img_klb',
    bankFullName: 'Ngân hàng TMCP Kiên Long',
    abbreviation: 'KienlongBank',
    issuerCode: '970452',
    code: '91353001',
  },
  {
    image: 'img_umee',
    bankFullName: 'Ngân hàng số UMEE by KienlongBank',
    abbreviation: 'UMEE',
    issuerCode: '963399',
    code: '91353001U',
  },
  {
    image: 'img_vab',
    bankFullName: 'Ngân hàng TMCP Việt Á ',
    abbreviation: 'Viet A Bank',
    issuerCode: '970427',
    code: '01355002',
  },
  {
    image: 'img_vietbank',
    bankFullName: 'Ngân hàng TMCP Việt Nam Thương Tín',
    abbreviation: 'Vietbank',
    issuerCode: '970433',
    code: '79356001',
  },
  {
    image: 'img_lpb',
    bankFullName: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    abbreviation: 'LPBank',
    issuerCode: '970449',
    code: '01357001',
  },
  {
    image: 'img_tpb',
    bankFullName: 'Ngân hàng TMCP Tiên Phong',
    abbreviation: 'TPBank',
    issuerCode: '970423',
    code: '01358001',
  },
  {
    image: 'img_bvb',
    bankFullName: 'Ngân hàng TMCP Bảo Việt',
    abbreviation: 'Bao Viet Bank',
    issuerCode: '970438',
    code: '01359001',
  },
  {
    image: 'img_pvc',
    bankFullName: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    abbreviation: 'PVcomBank',
    issuerCode: '970412',
    code: '01360002',
  },
  {
    image: 'img_vietqr_napas',
    bankFullName: 'CTCP TT QUOC GIA VIET NAM NAPAS',
    abbreviation: 'VietQR_NAPAS',
    issuerCode: '',
    code: '01401001',
  },
  {
    image: 'img_vid',
    bankFullName: 'Ngân hàng TNHH MTV Public Việt Nam',
    abbreviation: 'Public Bank Viet Nam',
    issuerCode: '970439',
    code: '01501001',
  },
  {
    image: 'img_ivb',
    bankFullName: 'Ngân hàng TNHH Indovina',
    abbreviation: 'Indovina Bank',
    issuerCode: '970434',
    code: '79502001',
  },
  {
    image: 'img_vrb',
    bankFullName: 'Liên doanh Việt - Nga',
    abbreviation: 'VRB',
    issuerCode: '970421',
    code: '01505001',
  },
  {
    image: 'img_siam',
    bankFullName: 'NH THE SIAM COMMERCIAL BANK PUBLIC',
    abbreviation: 'SIAM',
    issuerCode: '',
    code: '79600001',
  },
  {
    image: 'img_bpceiom',
    bankFullName: 'NH BPCEIOM CN TP HCM',
    abbreviation: 'BPCEIOM',
    issuerCode: '',
    code: '79601001',
  },
  {
    image: 'img_anz',
    bankFullName: 'Ngân hàng ANZ VIET NAM',
    abbreviation: 'ANZ ',
    issuerCode: '',
    code: '01602002',
  },
  {
    image: 'img_hlb',
    bankFullName: 'Ngân hàng TNHH MTV Hongleong Việt Nam',
    abbreviation: 'HLBank',
    issuerCode: '970442',
    code: '79603001',
  },
  {
    image: 'img_standard_chartered',
    bankFullName: 'Ngân hàng TNHH MTV Standard Chartered Việt Nam',
    abbreviation: 'Standard Chartered',
    issuerCode: '970410',
    code: '01604002',
  },
  {
    image: 'img_citibank',
    bankFullName: 'Ngân hàng Citibank Việt Nam',
    abbreviation: 'Citibank',
    issuerCode: '533948',
    code: '01605001',
  },
  {
    image: 'img_shbvn',
    bankFullName: 'Ngân hàng The Shanghai Commercial & Savings Bank',
    abbreviation: 'Shanghai Commercial & Savings Bank',
    issuerCode: '',
    code: '75606001',
  },
  {
    image: 'img_commercial',
    bankFullName: 'Ngân hàng First Commercial Bank Chi nhánh Hà Nội',
    abbreviation: 'First commercial HN',
    issuerCode: '',
    code: '01608001',
  },
  {
    image: 'img_maybank',
    bankFullName: 'Ngân hàng Malayan Banking Berhad',
    abbreviation: 'MAYBANK',
    issuerCode: '',
    code: '01609001',
  },
  {
    image: 'img_chinatrust',
    bankFullName: 'Ngân hàng TNHH CTBC Việt Nam',
    abbreviation: 'China Trust',
    issuerCode: '',
    code: '79611001',
  },
  {
    image: 'img_bangkok',
    bankFullName: 'BANGKOK BANK TP HCM',
    abbreviation: 'BANGKOK BANK HCM',
    issuerCode: '',
    code: '79612001',
  },
  {
    image: 'img_mizuho',
    bankFullName: 'Ngân hàng Mizuho Bank chi nhánh TP Hà Nội',
    abbreviation: 'Mizuho Hanoi',
    issuerCode: '',
    code: '01613001',
  },
  {
    image: 'img_bnp_paribas',
    bankFullName: 'Ngân hàng BNB PARIBAS chi nhánh HCM',
    abbreviation: 'BNP PARIBAS HCM',
    issuerCode: '963666',
    code: '79614001',
  },
  {
    image: 'img_communication',
    bankFullName: 'Bank Of Communications',
    abbreviation: 'BOC',
    issuerCode: '',
    code: '79615001',
  },
  {
    image: 'img_shbvn',
    bankFullName: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    abbreviation: 'Shinhan Bank',
    issuerCode: '970424',
    code: '79616001',
  },
  {
    image: 'img_hsbc',
    bankFullName: 'Ngân hàng HSBC Việt Nam',
    abbreviation: 'HSBC',
    issuerCode: '458761',
    code: '79617001',
  },
  {
    image: 'img_uob',
    bankFullName: 'UNITED OVERSEAR BANK HOI SO HCM',
    abbreviation: 'UNITED OVERSEAR BANK HCM',
    issuerCode: '',
    code: '79618001',
  },
  {
    image: 'img_deutsche',
    bankFullName: 'Ngân hàng Deutsche Bank AG',
    abbreviation: 'Deutsche Bank',
    issuerCode: '',
    code: '79619001',
  },
  {
    image: 'img_china',
    bankFullName: 'Ngân hàng Bank of China (hongkong) Limited - CN Hồ Chí Minh',
    abbreviation: 'BOCHK',
    issuerCode: '',
    code: '79620001',
  },
  {
    image: '',
    bankFullName: 'NH CREDIT AGRICOLE CIB CN TP HCM',
    abbreviation: 'NH CREDIT AGRICOLE CIB HCM',
    issuerCode: '',
    code: '79621001',
  },
  {
    image: 'img_tokyomitsubishi',
    bankFullName: 'Ngân hàng MUFG Bank CN TP HCM',
    abbreviation: 'BTMU HCM',
    issuerCode: '',
    code: '79622001',
  },
  {
    image: 'img_mega',
    bankFullName: 'Ngân hàng MEGA International Commercial Bank',
    abbreviation: 'MEGA ICBC',
    issuerCode: '',
    code: '79623001',
  },
  {
    image: 'img_chinese_ocbc',
    bankFullName: 'Ngân hàng Oversea - Chinese Banking Corp LTD',
    abbreviation: 'OCBC',
    issuerCode: '',
    code: '79625001',
  },
  {
    image: 'img_hana',
    bankFullName: 'Ngân hàng KEB Hana Bank CN Hà Nội',
    abbreviation: 'KEB Hana HN',
    issuerCode: '970467',
    code: '01626001',
  },
  {
    image: 'img_mcb',
    bankFullName: 'Ngân hàng JPMorgan Chase',
    abbreviation: 'JPMorgan Chase',
    issuerCode: '',
    code: '79627001',
  },
  {
    image: 'img_chinatrust',
    bankFullName: 'NH TNHH CTBC CN TP HO CHI MINH',
    abbreviation: 'NH TNHH CTBC HCM',
    issuerCode: '',
    code: '79629001',
  },
  {
    image: 'img_first_commercial',
    bankFullName: 'Ngân hàng First Commercial Bank Chi nhánh TP HCM',
    abbreviation: 'First commercial HCM',
    issuerCode: '',
    code: '79630001',
  },
  {
    image: 'img_kookmin',
    bankFullName: 'Ngân hàng Kookmin Chi nhánh HCMC',
    abbreviation: 'Kookmin Bank HCM',
    issuerCode: '970463',
    code: '79631001',
  },
  {
    image: 'img_sinopac',
    bankFullName: 'Ngân hàng SinoPac',
    abbreviation: 'SinoPac',
    issuerCode: '',
    code: '79632001',
  },
  {
    image: 'img_cathay',
    bankFullName: 'Ngân hàng Cathay United Bank Chi nhánh HCM',
    abbreviation: 'CUBHCM',
    issuerCode: '168999',
    code: '79634001',
  },
  {
    image: 'img_malayan',
    bankFullName: 'Malayan Banking Berhad',
    abbreviation: 'Malayan',
    issuerCode: '',
    code: '79635001',
  },
  {
    image: 'img_smbc',
    bankFullName: 'SMB CORPORATION',
    abbreviation: 'SMB CORPORATION',
    issuerCode: '',
    code: '01636001',
  },
  {
    image: 'img_bidc',
    bankFullName: 'Ngân hàng Đầu tư và Phát triển CAMPUCHIA',
    abbreviation: 'BIDC',
    issuerCode: '',
    code: '01638001',
  },
  {
    image: 'img_mizuho',
    bankFullName: 'Ngân hàng Mizuho Bank TP Hồ Chí Minh',
    abbreviation: 'Mizuho HCMC',
    issuerCode: '',
    code: '79639001',
  },
  {
    image: 'img_hua_nan',
    bankFullName: 'HUA NAN COMMERCIAL BANK TP HCM',
    abbreviation: 'HUA NAN COMMERCIAL HCM',
    issuerCode: '',
    code: '79640001',
  },
  {
    image: 'img_ibk',
    bankFullName: 'Ngân hàng Công nghiệp Hàn Quốc Chi nhánh HCM',
    abbreviation: 'Industribal Bank Korea HCM',
    issuerCode: '',
    code: '79641001',
  },
  {
    image: 'img_taipei',
    bankFullName: 'Ngân hàng Thương mại Tapei Fubon',
    abbreviation: 'TFCB',
    issuerCode: '',
    code: '01642001',
  },
  {
    image: 'img_hsbc',
    bankFullName: 'NH THE HONGKONG AND SHANGHAI CN HN',
    abbreviation: 'NH THE HONGKONG AND SHANGHAI HN',
    issuerCode: '',
    code: '01645001',
  },
  {
    image: 'img_bidc',
    bankFullName: 'NH DT VA PT CAMPUCHIA CN TP HCM',
    abbreviation: 'NH DT VA PT CAMPUCHIA HCM',
    issuerCode: '',
    code: '79648001',
  },
  {
    image: 'img_icbc',
    bankFullName: 'ICB OF CHINA CN HA NOI',
    abbreviation: 'ICB OF CHINA HN',
    issuerCode: '',
    code: '01649001',
  },
  {
    image: 'img_dbs',
    bankFullName: 'Ngân hàng Development Bank of Singapore Limited',
    abbreviation: 'DBS',
    issuerCode: '796500',
    code: '79650001',
  },
  {
    image: 'img_taipei',
    bankFullName: 'NH THUONG MAI TAIPEI FUBON CN TPHCM',
    abbreviation: 'NH THUONG MAI TAIPEI FUBON HCM',
    issuerCode: '',
    code: '79651001',
  },
  {
    image: 'img_ibk',
    bankFullName: 'IBK - chi nhánh Hà Nội',
    abbreviation: 'IBK HN',
    issuerCode: '970455',
    code: '01652001',
  },
  {
    image: 'img_tokyomitsubishi',
    bankFullName: 'Ngân hàng MUFG Bank CN Hà Nội',
    abbreviation: 'BTMU HN',
    issuerCode: '',
    code: '01653001',
  },
  {
    image: 'img_citibank',
    bankFullName: 'Ngân hàng Citibank TP HCM',
    abbreviation: 'Citibank HCM',
    issuerCode: '',
    code: '79654001',
  },
  {
    image: 'img_taipei',
    bankFullName: 'NH TAIPEI FUBON CN BINH DUONG',
    abbreviation: 'NH TAIPEI FUBON CN BINH DUONG',
    issuerCode: '',
    code: '74655001',
  },
  {
    image: 'img_hana',
    bankFullName: 'Ngân hàng KEB Hana Bank CN TP HCM',
    abbreviation: 'KEB Hana HCM',
    issuerCode: '970466',
    code: '79656001',
  },
  {
    image: 'img_bnp_paribas',
    bankFullName: 'Ngân hàng BNP Paribas Vietnam',
    abbreviation: 'BNP Paribas',
    issuerCode: '963668',
    code: '01657001',
  },
  {
    image: 'img_esun',
    bankFullName: 'NH TNHH E.SUN CN DONG NAI',
    abbreviation: 'NH TNHH E.SUN CN DONG NAI',
    issuerCode: '',
    code: '75658001',
  },
  {
    image: 'img_india',
    bankFullName: 'BANK OF INDIA CN TP HO CHI MINH',
    abbreviation: 'BANK OF INDIA HCM',
    issuerCode: '',
    code: '79659001',
  },
  {
    image: 'img_busan',
    bankFullName: 'NH BUSAN CN TP HO CHI MINH',
    abbreviation: 'NH BUSAN HCM',
    issuerCode: '',
    code: '79660001',
  },
  {
    image: 'img_cimb',
    bankFullName: 'Ngân hàng CIMB Việt Nam',
    abbreviation: 'CIMB',
    issuerCode: '422589',
    code: '01661001',
  },
  {
    image: 'img_nong_huyp',
    bankFullName: 'NONGHYUP - Chi nhánh Hà Nội',
    abbreviation: 'Nonghyup HN',
    issuerCode: '801011',
    code: '01662001',
  },
  {
    image: 'img_woori',
    bankFullName: 'Ngân hàng Woori Việt Nam',
    abbreviation: 'Woori Bank',
    issuerCode: '970457',
    code: '01663001',
  },
  {
    image: 'img_algricutural_china',
    bankFullName: 'Ngân hàng Nông nghiệp Trung Quốc chi nhánh Hà Nội',
    abbreviation: 'Agirculture Bank of China',
    issuerCode: '',
    code: '01664001',
  },
  {
    image: 'img_uob',
    bankFullName: 'Ngân hàng TNHH MTV OverSea Bank Việt Nam',
    abbreviation: 'UOB',
    issuerCode: '970458',
    code: '79665001',
  },
  {
    image: 'img_kookmin',
    bankFullName: 'Ngân hàng Kookmin Chi nhánh Hà Nội',
    abbreviation: 'Kookmin Bank HN',
    issuerCode: '970462',
    code: '01666001',
  },
  {
    image: 'img_bangkok',
    bankFullName: 'Ngân hàng TNHH MTYV Bangkok Đại chúng',
    abbreviation: 'Bangkok Bank',
    issuerCode: '',
    code: '01667001',
  },
  {
    image: '',
    bankFullName: 'NH IM CN TP HO CHI MINH',
    abbreviation: 'NH IM HCM',
    issuerCode: '',
    code: '79668001',
  },
  {
    image: 'img_kasikornbank',
    bankFullName: 'Ngân hàng Đại chúng TNHH Kasikorn bank chi nhánh HCM',
    abbreviation: 'KasikornBank HCM',
    issuerCode: '668888',
    code: '79669001',
  },
  {
    image: '',
    bankFullName: 'KHO BAC NHA NUOC',
    abbreviation: 'KHO BAC NHA NUOC',
    issuerCode: '',
    code: '01701001',
  },
  {
    image: '',
    bankFullName: 'CT CHO THUE TAI CHINH QUOC TE VN HSC',
    abbreviation: 'CT CHO THUE TAI CHINH QUOC TE VN HSC',
    issuerCode: '',
    code: '79803001',
  },
  {
    image: '',
    bankFullName: 'CT CHO THUE TAI CHINH KEXIM HSC',
    abbreviation: 'CT CHO THUE TAI CHINH KEXIM HSC',
    issuerCode: '',
    code: '79804001',
  },
  {
    image: '',
    bankFullName: 'CT TC TNHH MTV CONG DONG HSC',
    abbreviation: 'CT TC TNHH MTV CONG DONG HSC',
    issuerCode: '',
    code: '01805001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH CAO SU HOI SO CHINH',
    abbreviation: 'CT TAI CHINH CAO SU',
    issuerCode: '',
    code: '79806001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH BUU DIEN HOI SO CHINH',
    abbreviation: 'CT TAI CHINH BUU DIEN',
    issuerCode: '',
    code: '01807001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH JACCS HOI SO CHINH',
    abbreviation: 'CT TAI CHINH JACCS',
    issuerCode: '',
    code: '79808001',
  },
  {
    image: 'img_anz',
    bankFullName: 'CT CHO THUE TAI CHINH ANZ VTRAC HSC',
    abbreviation: 'CT CHO THUE TAI CHINH ANZ VTRAC HSC',
    issuerCode: '',
    code: '01816001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH HANDICO HOI SO CHINH',
    abbreviation: 'CT TAI CHINH HANDICO',
    issuerCode: '',
    code: '01818001',
  },
  {
    image: '',
    bankFullName: 'CT CHO THUE TAI CHINH TAU THUY HSC',
    abbreviation: 'CT CHO THUE TAI CHINH TAU THUY HSC',
    issuerCode: '',
    code: '01819001',
  },
  {
    image: '',
    bankFullName: 'CT CHO THUE TAI CHINH QUOC TE CHAILEASE HSC',
    abbreviation: 'CT CHO THUE TAI CHINH QUOC TE CHAILEASE HSC',
    issuerCode: '',
    code: '79820001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH NH PT TPHCM HSC',
    abbreviation: 'CT TAI CHINH NH PT TPHCM HSC',
    issuerCode: '',
    code: '79823001',
  },
  {
    image: 'img_svfc',
    bankFullName: 'Công ty Tài chính TNHH MTV Shinhan Việt Nam',
    abbreviation: 'SVFC',
    issuerCode: '',
    code: '79824001',
  },
  {
    image: '',
    bankFullName: 'CT CP TAI CHINH SONG DA HSC',
    abbreviation: 'CT CP TAI CHINH SONG DA HSC',
    issuerCode: '',
    code: '01825001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH CO PHAN DIEN LUC HSC',
    abbreviation: 'CT TAI CHINH CO PHAN DIEN LUC',
    issuerCode: '',
    code: '01826001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH TOYOTA HOI SO CHINH',
    abbreviation: 'CT TAI CHINH TOYOTA HOI SO CHINH',
    issuerCode: '',
    code: '79827001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH CO PHAN XI MANG HSC',
    abbreviation: 'CT TAI CHINH CO PHAN XI MANG HSC',
    issuerCode: '',
    code: '01828001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH TNHH MTV LOTTE VIET NAM',
    abbreviation: 'CT TAI CHINH TNHH MTV LOTTE VIET NAM',
    issuerCode: '',
    code: '01829001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH TNHH MTV HOME CREDIT VN HSC',
    abbreviation: 'CT TAI CHINH TNHH MTV HOME CREDIT VN HSC',
    issuerCode: '',
    code: '79830001',
  },
  {
    image: '',
    bankFullName: 'CT TAI CHINH VINACONEX VIETTEL HSC',
    abbreviation: 'CT TAI CHINH VINACONEX VIETTEL HSC',
    issuerCode: '',
    code: '01831001',
  },
  {
    image: 'img_ccf',
    bankFullName: 'Ngân hàng Hợp tác xã Việt Nam',
    abbreviation: 'Co-opBank',
    issuerCode: '970446',
    code: '01901001',
  },
  {
    image: '',
    bankFullName: 'QUY TDCS',
    abbreviation: 'QUY TDCS',
    issuerCode: '',
    code: '15902001',
  },
  {
    image: 'img_cake_by_vpbank',
    bankFullName: 'Ngân hàng số CAKE by VPBANK',
    abbreviation: 'CAKE by VPBank',
    issuerCode: '546034',
    code: '01309001C',
  },
  {
    image: 'img_u_bank',
    bankFullName: 'Ngân hàng số Ubank by VPBANK',
    abbreviation: 'Ubank by VPBank',
    issuerCode: '546035',
    code: '01309001U',
  },
  {
    image: 'img_vnpt_money',
    bankFullName: 'Ví điện tử VNPT Money',
    abbreviation: 'VNPT Money',
    issuerCode: '971011',
    code: '971011VM',
  },
  {
    image: 'img_viettel_money',
    bankFullName: 'Ví điện tử Viettel Money',
    abbreviation: 'Viettel Money',
    issuerCode: '971005',
    code: '971005VT',
  },
  {
    image: '',
    bankFullName: 'Công ty Tài chính TNHH MTV Mirae Asset Việt Nam',
    abbreviation: 'Mirae Asset',
    issuerCode: '977777',
    code: '977777MA',
  },
  {
    image: 'img_ibk',
    bankFullName: 'NH CONG NGHIEP HAN QUOC',
    abbreviation: 'IBK HCM',
    issuerCode: '970456',
    code: '01652001H',
  },
  {
    image: 'img_visa',
    bankFullName: 'VISA NH KHAC',
    abbreviation: 'VISA NH KHAC',
    issuerCode: '',
    code: '000100',
  },
  {
    image: 'img_mb',
    bankFullName: 'VISA MB',
    abbreviation: 'VISA MB',
    issuerCode: '',
    code: '000101',
  },
  {
    image: 'img_mastercard',
    bankFullName: 'MasterCard NH khác',
    abbreviation: 'MasterCard NH khác',
    issuerCode: '',
    code: '000200',
  },
  {
    image: 'img_mb',
    bankFullName: 'MasterCard MB',
    abbreviation: 'MasterCard MB',
    issuerCode: '',
    code: '000201',
  },
  {
    image: 'img_jcb',
    bankFullName: 'JCB NH khác',
    abbreviation: 'JCB NH khác',
    issuerCode: '',
    code: '000300',
  },
  {
    image: 'img_mb',
    bankFullName: 'JCB MB',
    abbreviation: 'JCB MB',
    issuerCode: '',
    code: '000301',
  },
  {
    image: 'img_napas247',
    bankFullName: 'Thẻ nội địa NH khác',
    abbreviation: 'Thẻ nội địa NH khác',
    issuerCode: '',
    code: '000400',
  },
  {
    image: 'img_mb',
    bankFullName: 'Thẻ nội địa MB',
    abbreviation: 'Thẻ nội địa MB',
    issuerCode: '',
    code: '000401',
  },
  {
    image: 'img_upi',
    bankFullName: 'UPI NH khác',
    abbreviation: 'UPI NH khác',
    issuerCode: '',
    code: '000500',
  },
  {
    image: 'img_upi_mb',
    bankFullName: 'UPI MB',
    abbreviation: 'UPI MB',
    issuerCode: '',
    code: '000501',
  }
]
